---
version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - Atoi
  - Codacy
  - containedctx
  - cyclop
  - errcheck
  - ewrap
  - Fprint
  - Fprintf
  - Fprintln
  - funlen
  - gocognit
  - ireturn
  - Newf
  - nolint
  - protogen
  - protoimpl
  - stdlib
  - stdlib's
  - strconv
  - workerpb
  - workerv
  - Wrapf
ignoreWords: []
import: []
