#!/usr/bin/env bash
set -e

# ######################################
# Ensure that a go module is initialized if not, skip the tests
# #######################################
ensure_go_module_initialized() {
	if [[ ! -f go.mod ]]; then
		echo "go.mod file not found, skipping the tests..."
		exit 0
	fi
}

# #######################################
# Run the pre-commit
# #######################################
hook() {
	ensure_go_module_initialized

	# get the root of the project
	local root_dir
	root_dir=$(git rev-parse --show-toplevel)

	local toolchain_version="1.25.6"
	if [[ -f "${root_dir}/.project-settings.env" ]]; then
		# shellcheck disable=SC1090
		source "${root_dir}/.project-settings.env"
		toolchain_version="${GO_VERSION:-${toolchain_version}}"
	fi

	# run the pre-commit hook
	pushd "${root_dir}" || exit
		GOTOOLCHAIN=go${toolchain_version}+auto go test -v -cover ./... || exit 1
	popd >/dev/null || exit
}

# #######################################
# Run the pre-commit if the ensure_go_module_initialized() function returns 0
# #######################################
ensure_go_module_initialized
hook
