// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: worker/v1/admin.proto

package workerpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetOverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewRequest) Reset() {
	*x = GetOverviewRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewRequest) ProtoMessage() {}

func (x *GetOverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewRequest.ProtoReflect.Descriptor instead.
func (*GetOverviewRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{0}
}

type OverviewStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActiveWorkers int32                  `protobuf:"varint,1,opt,name=active_workers,json=activeWorkers,proto3" json:"active_workers,omitempty"`
	QueuedTasks   int64                  `protobuf:"varint,2,opt,name=queued_tasks,json=queuedTasks,proto3" json:"queued_tasks,omitempty"`
	Queues        int32                  `protobuf:"varint,3,opt,name=queues,proto3" json:"queues,omitempty"`
	AvgLatencyMs  int64                  `protobuf:"varint,4,opt,name=avg_latency_ms,json=avgLatencyMs,proto3" json:"avg_latency_ms,omitempty"`
	P95LatencyMs  int64                  `protobuf:"varint,5,opt,name=p95_latency_ms,json=p95LatencyMs,proto3" json:"p95_latency_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewStats) Reset() {
	*x = OverviewStats{}
	mi := &file_worker_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewStats) ProtoMessage() {}

func (x *OverviewStats) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewStats.ProtoReflect.Descriptor instead.
func (*OverviewStats) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *OverviewStats) GetActiveWorkers() int32 {
	if x != nil {
		return x.ActiveWorkers
	}
	return 0
}

func (x *OverviewStats) GetQueuedTasks() int64 {
	if x != nil {
		return x.QueuedTasks
	}
	return 0
}

func (x *OverviewStats) GetQueues() int32 {
	if x != nil {
		return x.Queues
	}
	return 0
}

func (x *OverviewStats) GetAvgLatencyMs() int64 {
	if x != nil {
		return x.AvgLatencyMs
	}
	return 0
}

func (x *OverviewStats) GetP95LatencyMs() int64 {
	if x != nil {
		return x.P95LatencyMs
	}
	return 0
}

type CoordinationStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GlobalRateLimit string                 `protobuf:"bytes,1,opt,name=global_rate_limit,json=globalRateLimit,proto3" json:"global_rate_limit,omitempty"`
	LeaderLock      string                 `protobuf:"bytes,2,opt,name=leader_lock,json=leaderLock,proto3" json:"leader_lock,omitempty"`
	Lease           string                 `protobuf:"bytes,3,opt,name=lease,proto3" json:"lease,omitempty"`
	Paused          bool                   `protobuf:"varint,4,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CoordinationStatus) Reset() {
	*x = CoordinationStatus{}
	mi := &file_worker_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoordinationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoordinationStatus) ProtoMessage() {}

func (x *CoordinationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoordinationStatus.ProtoReflect.Descriptor instead.
func (*CoordinationStatus) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{2}
}

func (x *CoordinationStatus) GetGlobalRateLimit() string {
	if x != nil {
		return x.GlobalRateLimit
	}
	return ""
}

func (x *CoordinationStatus) GetLeaderLock() string {
	if x != nil {
		return x.LeaderLock
	}
	return ""
}

func (x *CoordinationStatus) GetLease() string {
	if x != nil {
		return x.Lease
	}
	return ""
}

func (x *CoordinationStatus) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type AdminActionCounters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pause         int64                  `protobuf:"varint,1,opt,name=pause,proto3" json:"pause,omitempty"`
	Resume        int64                  `protobuf:"varint,2,opt,name=resume,proto3" json:"resume,omitempty"`
	Replay        int64                  `protobuf:"varint,3,opt,name=replay,proto3" json:"replay,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminActionCounters) Reset() {
	*x = AdminActionCounters{}
	mi := &file_worker_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminActionCounters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminActionCounters) ProtoMessage() {}

func (x *AdminActionCounters) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminActionCounters.ProtoReflect.Descriptor instead.
func (*AdminActionCounters) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *AdminActionCounters) GetPause() int64 {
	if x != nil {
		return x.Pause
	}
	return 0
}

func (x *AdminActionCounters) GetResume() int64 {
	if x != nil {
		return x.Resume
	}
	return 0
}

func (x *AdminActionCounters) GetReplay() int64 {
	if x != nil {
		return x.Replay
	}
	return 0
}

type GetOverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *OverviewStats         `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	Coordination  *CoordinationStatus    `protobuf:"bytes,2,opt,name=coordination,proto3" json:"coordination,omitempty"`
	Actions       *AdminActionCounters   `protobuf:"bytes,3,opt,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOverviewResponse) Reset() {
	*x = GetOverviewResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOverviewResponse) ProtoMessage() {}

func (x *GetOverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOverviewResponse.ProtoReflect.Descriptor instead.
func (*GetOverviewResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{4}
}

func (x *GetOverviewResponse) GetStats() *OverviewStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *GetOverviewResponse) GetCoordination() *CoordinationStatus {
	if x != nil {
		return x.Coordination
	}
	return nil
}

func (x *GetOverviewResponse) GetActions() *AdminActionCounters {
	if x != nil {
		return x.Actions
	}
	return nil
}

type GetHealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthRequest) Reset() {
	*x = GetHealthRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthRequest) ProtoMessage() {}

func (x *GetHealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthRequest.ProtoReflect.Descriptor instead.
func (*GetHealthRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{5}
}

type GetHealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Commit        string                 `protobuf:"bytes,3,opt,name=commit,proto3" json:"commit,omitempty"`
	BuildTime     string                 `protobuf:"bytes,4,opt,name=build_time,json=buildTime,proto3" json:"build_time,omitempty"`
	GoVersion     string                 `protobuf:"bytes,5,opt,name=go_version,json=goVersion,proto3" json:"go_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHealthResponse) Reset() {
	*x = GetHealthResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHealthResponse) ProtoMessage() {}

func (x *GetHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHealthResponse.ProtoReflect.Descriptor instead.
func (*GetHealthResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{6}
}

func (x *GetHealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetHealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *GetHealthResponse) GetCommit() string {
	if x != nil {
		return x.Commit
	}
	return ""
}

func (x *GetHealthResponse) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

func (x *GetHealthResponse) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

type QueueSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ready         int64                  `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Processing    int64                  `protobuf:"varint,3,opt,name=processing,proto3" json:"processing,omitempty"`
	Dead          int64                  `protobuf:"varint,4,opt,name=dead,proto3" json:"dead,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueSummary) Reset() {
	*x = QueueSummary{}
	mi := &file_worker_v1_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueSummary) ProtoMessage() {}

func (x *QueueSummary) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueSummary.ProtoReflect.Descriptor instead.
func (*QueueSummary) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{7}
}

func (x *QueueSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueSummary) GetReady() int64 {
	if x != nil {
		return x.Ready
	}
	return 0
}

func (x *QueueSummary) GetProcessing() int64 {
	if x != nil {
		return x.Processing
	}
	return 0
}

func (x *QueueSummary) GetDead() int64 {
	if x != nil {
		return x.Dead
	}
	return 0
}

func (x *QueueSummary) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type ListQueuesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesRequest) Reset() {
	*x = ListQueuesRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesRequest) ProtoMessage() {}

func (x *ListQueuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesRequest.ProtoReflect.Descriptor instead.
func (*ListQueuesRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{8}
}

type ListQueuesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queues        []*QueueSummary        `protobuf:"bytes,1,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListQueuesResponse.ProtoReflect.Descriptor instead.
func (*ListQueuesResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{9}
}

func (x *ListQueuesResponse) GetQueues() []*QueueSummary {
	if x != nil {
		return x.Queues
	}
	return nil
}

type GetQueueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueRequest) Reset() {
	*x = GetQueueRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueRequest) ProtoMessage() {}

func (x *GetQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueRequest.ProtoReflect.Descriptor instead.
func (*GetQueueRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{10}
}

func (x *GetQueueRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetQueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *QueueSummary          `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetQueueResponse) Reset() {
	*x = GetQueueResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueResponse) ProtoMessage() {}

func (x *GetQueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetQueueResponse.ProtoReflect.Descriptor instead.
func (*GetQueueResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{11}
}

func (x *GetQueueResponse) GetQueue() *QueueSummary {
	if x != nil {
		return x.Queue
	}
	return nil
}

type UpdateQueueWeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Weight        int32                  `protobuf:"varint,2,opt,name=weight,proto3" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQueueWeightRequest) Reset() {
	*x = UpdateQueueWeightRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQueueWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQueueWeightRequest) ProtoMessage() {}

func (x *UpdateQueueWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQueueWeightRequest.ProtoReflect.Descriptor instead.
func (*UpdateQueueWeightRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateQueueWeightRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateQueueWeightRequest) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type UpdateQueueWeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *QueueSummary          `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateQueueWeightResponse) Reset() {
	*x = UpdateQueueWeightResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateQueueWeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateQueueWeightResponse) ProtoMessage() {}

func (x *UpdateQueueWeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateQueueWeightResponse.ProtoReflect.Descriptor instead.
func (*UpdateQueueWeightResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateQueueWeightResponse) GetQueue() *QueueSummary {
	if x != nil {
		return x.Queue
	}
	return nil
}

type ResetQueueWeightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetQueueWeightRequest) Reset() {
	*x = ResetQueueWeightRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetQueueWeightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetQueueWeightRequest) ProtoMessage() {}

func (x *ResetQueueWeightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetQueueWeightRequest.ProtoReflect.Descriptor instead.
func (*ResetQueueWeightRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ResetQueueWeightRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ResetQueueWeightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Queue         *QueueSummary          `protobuf:"bytes,1,opt,name=queue,proto3" json:"queue,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetQueueWeightResponse) Reset() {
	*x = ResetQueueWeightResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetQueueWeightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetQueueWeightResponse) ProtoMessage() {}

func (x *ResetQueueWeightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetQueueWeightResponse.ProtoReflect.Descriptor instead.
func (*ResetQueueWeightResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ResetQueueWeightResponse) GetQueue() *QueueSummary {
	if x != nil {
		return x.Queue
	}
	return nil
}

type ScheduleEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          string                 `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	NextRunMs     int64                  `protobuf:"varint,3,opt,name=next_run_ms,json=nextRunMs,proto3" json:"next_run_ms,omitempty"`
	LastRunMs     int64                  `protobuf:"varint,4,opt,name=last_run_ms,json=lastRunMs,proto3" json:"last_run_ms,omitempty"`
	Durable       bool                   `protobuf:"varint,5,opt,name=durable,proto3" json:"durable,omitempty"`
	Paused        bool                   `protobuf:"varint,6,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEntry) Reset() {
	*x = ScheduleEntry{}
	mi := &file_worker_v1_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEntry) ProtoMessage() {}

func (x *ScheduleEntry) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEntry.ProtoReflect.Descriptor instead.
func (*ScheduleEntry) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ScheduleEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduleEntry) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *ScheduleEntry) GetNextRunMs() int64 {
	if x != nil {
		return x.NextRunMs
	}
	return 0
}

func (x *ScheduleEntry) GetLastRunMs() int64 {
	if x != nil {
		return x.LastRunMs
	}
	return 0
}

func (x *ScheduleEntry) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *ScheduleEntry) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type ScheduleFactory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Durable       bool                   `protobuf:"varint,2,opt,name=durable,proto3" json:"durable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleFactory) Reset() {
	*x = ScheduleFactory{}
	mi := &file_worker_v1_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleFactory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleFactory) ProtoMessage() {}

func (x *ScheduleFactory) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleFactory.ProtoReflect.Descriptor instead.
func (*ScheduleFactory) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ScheduleFactory) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduleFactory) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

type ScheduleEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Spec          string                 `protobuf:"bytes,3,opt,name=spec,proto3" json:"spec,omitempty"`
	Durable       bool                   `protobuf:"varint,4,opt,name=durable,proto3" json:"durable,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Queue         string                 `protobuf:"bytes,6,opt,name=queue,proto3" json:"queue,omitempty"`
	StartedAtMs   int64                  `protobuf:"varint,7,opt,name=started_at_ms,json=startedAtMs,proto3" json:"started_at_ms,omitempty"`
	FinishedAtMs  int64                  `protobuf:"varint,8,opt,name=finished_at_ms,json=finishedAtMs,proto3" json:"finished_at_ms,omitempty"`
	DurationMs    int64                  `protobuf:"varint,9,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	Result        string                 `protobuf:"bytes,10,opt,name=result,proto3" json:"result,omitempty"`
	Error         string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,12,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleEvent) Reset() {
	*x = ScheduleEvent{}
	mi := &file_worker_v1_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleEvent) ProtoMessage() {}

func (x *ScheduleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleEvent.ProtoReflect.Descriptor instead.
func (*ScheduleEvent) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ScheduleEvent) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ScheduleEvent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScheduleEvent) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *ScheduleEvent) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

func (x *ScheduleEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ScheduleEvent) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ScheduleEvent) GetStartedAtMs() int64 {
	if x != nil {
		return x.StartedAtMs
	}
	return 0
}

func (x *ScheduleEvent) GetFinishedAtMs() int64 {
	if x != nil {
		return x.FinishedAtMs
	}
	return 0
}

func (x *ScheduleEvent) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *ScheduleEvent) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ScheduleEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ScheduleEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ListScheduleFactoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduleFactoriesRequest) Reset() {
	*x = ListScheduleFactoriesRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleFactoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleFactoriesRequest) ProtoMessage() {}

func (x *ListScheduleFactoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleFactoriesRequest.ProtoReflect.Descriptor instead.
func (*ListScheduleFactoriesRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{19}
}

type ListScheduleFactoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Factories     []*ScheduleFactory     `protobuf:"bytes,1,rep,name=factories,proto3" json:"factories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduleFactoriesResponse) Reset() {
	*x = ListScheduleFactoriesResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleFactoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleFactoriesResponse) ProtoMessage() {}

func (x *ListScheduleFactoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleFactoriesResponse.ProtoReflect.Descriptor instead.
func (*ListScheduleFactoriesResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{20}
}

func (x *ListScheduleFactoriesResponse) GetFactories() []*ScheduleFactory {
	if x != nil {
		return x.Factories
	}
	return nil
}

type ListScheduleEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduleEventsRequest) Reset() {
	*x = ListScheduleEventsRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleEventsRequest) ProtoMessage() {}

func (x *ListScheduleEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleEventsRequest.ProtoReflect.Descriptor instead.
func (*ListScheduleEventsRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{21}
}

func (x *ListScheduleEventsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListScheduleEventsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListScheduleEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*ScheduleEvent       `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListScheduleEventsResponse) Reset() {
	*x = ListScheduleEventsResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListScheduleEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListScheduleEventsResponse) ProtoMessage() {}

func (x *ListScheduleEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListScheduleEventsResponse.ProtoReflect.Descriptor instead.
func (*ListScheduleEventsResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{22}
}

func (x *ListScheduleEventsResponse) GetEvents() []*ScheduleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type ListSchedulesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesRequest) Reset() {
	*x = ListSchedulesRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesRequest) ProtoMessage() {}

func (x *ListSchedulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesRequest.ProtoReflect.Descriptor instead.
func (*ListSchedulesRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{23}
}

type ListSchedulesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedules     []*ScheduleEntry       `protobuf:"bytes,1,rep,name=schedules,proto3" json:"schedules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSchedulesResponse) Reset() {
	*x = ListSchedulesResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSchedulesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSchedulesResponse) ProtoMessage() {}

func (x *ListSchedulesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSchedulesResponse.ProtoReflect.Descriptor instead.
func (*ListSchedulesResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{24}
}

func (x *ListSchedulesResponse) GetSchedules() []*ScheduleEntry {
	if x != nil {
		return x.Schedules
	}
	return nil
}

type CreateScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Spec          string                 `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	Durable       bool                   `protobuf:"varint,3,opt,name=durable,proto3" json:"durable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleRequest) Reset() {
	*x = CreateScheduleRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleRequest) ProtoMessage() {}

func (x *CreateScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleRequest.ProtoReflect.Descriptor instead.
func (*CreateScheduleRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{25}
}

func (x *CreateScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateScheduleRequest) GetSpec() string {
	if x != nil {
		return x.Spec
	}
	return ""
}

func (x *CreateScheduleRequest) GetDurable() bool {
	if x != nil {
		return x.Durable
	}
	return false
}

type CreateScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *ScheduleEntry         `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateScheduleResponse) Reset() {
	*x = CreateScheduleResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateScheduleResponse) ProtoMessage() {}

func (x *CreateScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateScheduleResponse.ProtoReflect.Descriptor instead.
func (*CreateScheduleResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{26}
}

func (x *CreateScheduleResponse) GetSchedule() *ScheduleEntry {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type DeleteScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleRequest) Reset() {
	*x = DeleteScheduleRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleRequest) ProtoMessage() {}

func (x *DeleteScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleRequest.ProtoReflect.Descriptor instead.
func (*DeleteScheduleRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{27}
}

func (x *DeleteScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteScheduleResponse) Reset() {
	*x = DeleteScheduleResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteScheduleResponse) ProtoMessage() {}

func (x *DeleteScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteScheduleResponse.ProtoReflect.Descriptor instead.
func (*DeleteScheduleResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{28}
}

func (x *DeleteScheduleResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type PauseScheduleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Paused        bool                   `protobuf:"varint,2,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseScheduleRequest) Reset() {
	*x = PauseScheduleRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseScheduleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseScheduleRequest) ProtoMessage() {}

func (x *PauseScheduleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseScheduleRequest.ProtoReflect.Descriptor instead.
func (*PauseScheduleRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{29}
}

func (x *PauseScheduleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PauseScheduleRequest) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type PauseScheduleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schedule      *ScheduleEntry         `protobuf:"bytes,1,opt,name=schedule,proto3" json:"schedule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseScheduleResponse) Reset() {
	*x = PauseScheduleResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseScheduleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseScheduleResponse) ProtoMessage() {}

func (x *PauseScheduleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseScheduleResponse.ProtoReflect.Descriptor instead.
func (*PauseScheduleResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{30}
}

func (x *PauseScheduleResponse) GetSchedule() *ScheduleEntry {
	if x != nil {
		return x.Schedule
	}
	return nil
}

type DLQEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Queue         string                 `protobuf:"bytes,2,opt,name=queue,proto3" json:"queue,omitempty"`
	Handler       string                 `protobuf:"bytes,3,opt,name=handler,proto3" json:"handler,omitempty"`
	Attempts      int32                  `protobuf:"varint,4,opt,name=attempts,proto3" json:"attempts,omitempty"`
	AgeMs         int64                  `protobuf:"varint,5,opt,name=age_ms,json=ageMs,proto3" json:"age_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DLQEntry) Reset() {
	*x = DLQEntry{}
	mi := &file_worker_v1_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DLQEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DLQEntry) ProtoMessage() {}

func (x *DLQEntry) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DLQEntry.ProtoReflect.Descriptor instead.
func (*DLQEntry) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{31}
}

func (x *DLQEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DLQEntry) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *DLQEntry) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *DLQEntry) GetAttempts() int32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DLQEntry) GetAgeMs() int64 {
	if x != nil {
		return x.AgeMs
	}
	return 0
}

type ListDLQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Queue         string                 `protobuf:"bytes,3,opt,name=queue,proto3" json:"queue,omitempty"`
	Handler       string                 `protobuf:"bytes,4,opt,name=handler,proto3" json:"handler,omitempty"`
	Query         string                 `protobuf:"bytes,5,opt,name=query,proto3" json:"query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQRequest) Reset() {
	*x = ListDLQRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQRequest) ProtoMessage() {}

func (x *ListDLQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQRequest.ProtoReflect.Descriptor instead.
func (*ListDLQRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{32}
}

func (x *ListDLQRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListDLQRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListDLQRequest) GetQueue() string {
	if x != nil {
		return x.Queue
	}
	return ""
}

func (x *ListDLQRequest) GetHandler() string {
	if x != nil {
		return x.Handler
	}
	return ""
}

func (x *ListDLQRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

type ListDLQResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*DLQEntry            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDLQResponse) Reset() {
	*x = ListDLQResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDLQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDLQResponse) ProtoMessage() {}

func (x *ListDLQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDLQResponse.ProtoReflect.Descriptor instead.
func (*ListDLQResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{33}
}

func (x *ListDLQResponse) GetEntries() []*DLQEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListDLQResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PauseDequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseDequeueRequest) Reset() {
	*x = PauseDequeueRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseDequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseDequeueRequest) ProtoMessage() {}

func (x *PauseDequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseDequeueRequest.ProtoReflect.Descriptor instead.
func (*PauseDequeueRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{34}
}

type PauseDequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paused        bool                   `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PauseDequeueResponse) Reset() {
	*x = PauseDequeueResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PauseDequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PauseDequeueResponse) ProtoMessage() {}

func (x *PauseDequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PauseDequeueResponse.ProtoReflect.Descriptor instead.
func (*PauseDequeueResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{35}
}

func (x *PauseDequeueResponse) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type ResumeDequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeDequeueRequest) Reset() {
	*x = ResumeDequeueRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDequeueRequest) ProtoMessage() {}

func (x *ResumeDequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDequeueRequest.ProtoReflect.Descriptor instead.
func (*ResumeDequeueRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{36}
}

type ResumeDequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Paused        bool                   `protobuf:"varint,1,opt,name=paused,proto3" json:"paused,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResumeDequeueResponse) Reset() {
	*x = ResumeDequeueResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeDequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeDequeueResponse) ProtoMessage() {}

func (x *ResumeDequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResumeDequeueResponse.ProtoReflect.Descriptor instead.
func (*ResumeDequeueResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{37}
}

func (x *ResumeDequeueResponse) GetPaused() bool {
	if x != nil {
		return x.Paused
	}
	return false
}

type ReplayDLQRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDLQRequest) Reset() {
	*x = ReplayDLQRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDLQRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDLQRequest) ProtoMessage() {}

func (x *ReplayDLQRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDLQRequest.ProtoReflect.Descriptor instead.
func (*ReplayDLQRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{38}
}

func (x *ReplayDLQRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ReplayDLQResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moved         int32                  `protobuf:"varint,1,opt,name=moved,proto3" json:"moved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDLQResponse) Reset() {
	*x = ReplayDLQResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDLQResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDLQResponse) ProtoMessage() {}

func (x *ReplayDLQResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDLQResponse.ProtoReflect.Descriptor instead.
func (*ReplayDLQResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{39}
}

func (x *ReplayDLQResponse) GetMoved() int32 {
	if x != nil {
		return x.Moved
	}
	return 0
}

type ReplayDLQByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDLQByIDRequest) Reset() {
	*x = ReplayDLQByIDRequest{}
	mi := &file_worker_v1_admin_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDLQByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDLQByIDRequest) ProtoMessage() {}

func (x *ReplayDLQByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDLQByIDRequest.ProtoReflect.Descriptor instead.
func (*ReplayDLQByIDRequest) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{40}
}

func (x *ReplayDLQByIDRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type ReplayDLQByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Moved         int32                  `protobuf:"varint,1,opt,name=moved,proto3" json:"moved,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplayDLQByIDResponse) Reset() {
	*x = ReplayDLQByIDResponse{}
	mi := &file_worker_v1_admin_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplayDLQByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplayDLQByIDResponse) ProtoMessage() {}

func (x *ReplayDLQByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_admin_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplayDLQByIDResponse.ProtoReflect.Descriptor instead.
func (*ReplayDLQByIDResponse) Descriptor() ([]byte, []int) {
	return file_worker_v1_admin_proto_rawDescGZIP(), []int{41}
}

func (x *ReplayDLQByIDResponse) GetMoved() int32 {
	if x != nil {
		return x.Moved
	}
	return 0
}

var File_worker_v1_admin_proto protoreflect.FileDescriptor

const file_worker_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x15worker/v1/admin.proto\x12\tworker.v1\"\x14\n" +
	"\x12GetOverviewRequest\"\xbd\x01\n" +
	"\rOverviewStats\x12%\n" +
	"\x0eactive_workers\x18\x01 \x01(\x05R\ractiveWorkers\x12!\n" +
	"\fqueued_tasks\x18\x02 \x01(\x03R\vqueuedTasks\x12\x16\n" +
	"\x06queues\x18\x03 \x01(\x05R\x06queues\x12$\n" +
	"\x0eavg_latency_ms\x18\x04 \x01(\x03R\favgLatencyMs\x12$\n" +
	"\x0ep95_latency_ms\x18\x05 \x01(\x03R\fp95LatencyMs\"\x8f\x01\n" +
	"\x12CoordinationStatus\x12*\n" +
	"\x11global_rate_limit\x18\x01 \x01(\tR\x0fglobalRateLimit\x12\x1f\n" +
	"\vleader_lock\x18\x02 \x01(\tR\n" +
	"leaderLock\x12\x14\n" +
	"\x05lease\x18\x03 \x01(\tR\x05lease\x12\x16\n" +
	"\x06paused\x18\x04 \x01(\bR\x06paused\"[\n" +
	"\x13AdminActionCounters\x12\x14\n" +
	"\x05pause\x18\x01 \x01(\x03R\x05pause\x12\x16\n" +
	"\x06resume\x18\x02 \x01(\x03R\x06resume\x12\x16\n" +
	"\x06replay\x18\x03 \x01(\x03R\x06replay\"\xc2\x01\n" +
	"\x13GetOverviewResponse\x12.\n" +
	"\x05stats\x18\x01 \x01(\v2\x18.worker.v1.OverviewStatsR\x05stats\x12A\n" +
	"\fcoordination\x18\x02 \x01(\v2\x1d.worker.v1.CoordinationStatusR\fcoordination\x128\n" +
	"\aactions\x18\x03 \x01(\v2\x1e.worker.v1.AdminActionCountersR\aactions\"\x12\n" +
	"\x10GetHealthRequest\"\x9b\x01\n" +
	"\x11GetHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x16\n" +
	"\x06commit\x18\x03 \x01(\tR\x06commit\x12\x1d\n" +
	"\n" +
	"build_time\x18\x04 \x01(\tR\tbuildTime\x12\x1d\n" +
	"\n" +
	"go_version\x18\x05 \x01(\tR\tgoVersion\"\x84\x01\n" +
	"\fQueueSummary\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\x03R\x05ready\x12\x1e\n" +
	"\n" +
	"processing\x18\x03 \x01(\x03R\n" +
	"processing\x12\x12\n" +
	"\x04dead\x18\x04 \x01(\x03R\x04dead\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x05R\x06weight\"\x13\n" +
	"\x11ListQueuesRequest\"E\n" +
	"\x12ListQueuesResponse\x12/\n" +
	"\x06queues\x18\x01 \x03(\v2\x17.worker.v1.QueueSummaryR\x06queues\"%\n" +
	"\x0fGetQueueRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"A\n" +
	"\x10GetQueueResponse\x12-\n" +
	"\x05queue\x18\x01 \x01(\v2\x17.worker.v1.QueueSummaryR\x05queue\"F\n" +
	"\x18UpdateQueueWeightRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06weight\x18\x02 \x01(\x05R\x06weight\"J\n" +
	"\x19UpdateQueueWeightResponse\x12-\n" +
	"\x05queue\x18\x01 \x01(\v2\x17.worker.v1.QueueSummaryR\x05queue\"-\n" +
	"\x17ResetQueueWeightRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"I\n" +
	"\x18ResetQueueWeightResponse\x12-\n" +
	"\x05queue\x18\x01 \x01(\v2\x17.worker.v1.QueueSummaryR\x05queue\"\xa9\x01\n" +
	"\rScheduleEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04spec\x18\x02 \x01(\tR\x04spec\x12\x1e\n" +
	"\vnext_run_ms\x18\x03 \x01(\x03R\tnextRunMs\x12\x1e\n" +
	"\vlast_run_ms\x18\x04 \x01(\x03R\tlastRunMs\x12\x18\n" +
	"\adurable\x18\x05 \x01(\bR\adurable\x12\x16\n" +
	"\x06paused\x18\x06 \x01(\bR\x06paused\"?\n" +
	"\x0fScheduleFactory\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\adurable\x18\x02 \x01(\bR\adurable\"\xb2\x03\n" +
	"\rScheduleEvent\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04spec\x18\x03 \x01(\tR\x04spec\x12\x18\n" +
	"\adurable\x18\x04 \x01(\bR\adurable\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x14\n" +
	"\x05queue\x18\x06 \x01(\tR\x05queue\x12\"\n" +
	"\rstarted_at_ms\x18\a \x01(\x03R\vstartedAtMs\x12$\n" +
	"\x0efinished_at_ms\x18\b \x01(\x03R\ffinishedAtMs\x12\x1f\n" +
	"\vduration_ms\x18\t \x01(\x03R\n" +
	"durationMs\x12\x16\n" +
	"\x06result\x18\n" +
	" \x01(\tR\x06result\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12B\n" +
	"\bmetadata\x18\f \x03(\v2&.worker.v1.ScheduleEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x1e\n" +
	"\x1cListScheduleFactoriesRequest\"Y\n" +
	"\x1dListScheduleFactoriesResponse\x128\n" +
	"\tfactories\x18\x01 \x03(\v2\x1a.worker.v1.ScheduleFactoryR\tfactories\"E\n" +
	"\x19ListScheduleEventsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"N\n" +
	"\x1aListScheduleEventsResponse\x120\n" +
	"\x06events\x18\x01 \x03(\v2\x18.worker.v1.ScheduleEventR\x06events\"\x16\n" +
	"\x14ListSchedulesRequest\"O\n" +
	"\x15ListSchedulesResponse\x126\n" +
	"\tschedules\x18\x01 \x03(\v2\x18.worker.v1.ScheduleEntryR\tschedules\"Y\n" +
	"\x15CreateScheduleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04spec\x18\x02 \x01(\tR\x04spec\x12\x18\n" +
	"\adurable\x18\x03 \x01(\bR\adurable\"N\n" +
	"\x16CreateScheduleResponse\x124\n" +
	"\bschedule\x18\x01 \x01(\v2\x18.worker.v1.ScheduleEntryR\bschedule\"+\n" +
	"\x15DeleteScheduleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"2\n" +
	"\x16DeleteScheduleResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"B\n" +
	"\x14PauseScheduleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06paused\x18\x02 \x01(\bR\x06paused\"M\n" +
	"\x15PauseScheduleResponse\x124\n" +
	"\bschedule\x18\x01 \x01(\v2\x18.worker.v1.ScheduleEntryR\bschedule\"}\n" +
	"\bDLQEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05queue\x18\x02 \x01(\tR\x05queue\x12\x18\n" +
	"\ahandler\x18\x03 \x01(\tR\ahandler\x12\x1a\n" +
	"\battempts\x18\x04 \x01(\x05R\battempts\x12\x15\n" +
	"\x06age_ms\x18\x05 \x01(\x03R\x05ageMs\"\x84\x01\n" +
	"\x0eListDLQRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x14\n" +
	"\x05queue\x18\x03 \x01(\tR\x05queue\x12\x18\n" +
	"\ahandler\x18\x04 \x01(\tR\ahandler\x12\x14\n" +
	"\x05query\x18\x05 \x01(\tR\x05query\"V\n" +
	"\x0fListDLQResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.worker.v1.DLQEntryR\aentries\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\"\x15\n" +
	"\x13PauseDequeueRequest\".\n" +
	"\x14PauseDequeueResponse\x12\x16\n" +
	"\x06paused\x18\x01 \x01(\bR\x06paused\"\x16\n" +
	"\x14ResumeDequeueRequest\"/\n" +
	"\x15ResumeDequeueResponse\x12\x16\n" +
	"\x06paused\x18\x01 \x01(\bR\x06paused\"(\n" +
	"\x10ReplayDLQRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\")\n" +
	"\x11ReplayDLQResponse\x12\x14\n" +
	"\x05moved\x18\x01 \x01(\x05R\x05moved\"(\n" +
	"\x14ReplayDLQByIDRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"-\n" +
	"\x15ReplayDLQByIDResponse\x12\x14\n" +
	"\x05moved\x18\x01 \x01(\x05R\x05moved2\x99\v\n" +
	"\fAdminService\x12F\n" +
	"\tGetHealth\x12\x1b.worker.v1.GetHealthRequest\x1a\x1c.worker.v1.GetHealthResponse\x12L\n" +
	"\vGetOverview\x12\x1d.worker.v1.GetOverviewRequest\x1a\x1e.worker.v1.GetOverviewResponse\x12I\n" +
	"\n" +
	"ListQueues\x12\x1c.worker.v1.ListQueuesRequest\x1a\x1d.worker.v1.ListQueuesResponse\x12C\n" +
	"\bGetQueue\x12\x1a.worker.v1.GetQueueRequest\x1a\x1b.worker.v1.GetQueueResponse\x12^\n" +
	"\x11UpdateQueueWeight\x12#.worker.v1.UpdateQueueWeightRequest\x1a$.worker.v1.UpdateQueueWeightResponse\x12[\n" +
	"\x10ResetQueueWeight\x12\".worker.v1.ResetQueueWeightRequest\x1a#.worker.v1.ResetQueueWeightResponse\x12j\n" +
	"\x15ListScheduleFactories\x12'.worker.v1.ListScheduleFactoriesRequest\x1a(.worker.v1.ListScheduleFactoriesResponse\x12a\n" +
	"\x12ListScheduleEvents\x12$.worker.v1.ListScheduleEventsRequest\x1a%.worker.v1.ListScheduleEventsResponse\x12R\n" +
	"\rListSchedules\x12\x1f.worker.v1.ListSchedulesRequest\x1a .worker.v1.ListSchedulesResponse\x12U\n" +
	"\x0eCreateSchedule\x12 .worker.v1.CreateScheduleRequest\x1a!.worker.v1.CreateScheduleResponse\x12U\n" +
	"\x0eDeleteSchedule\x12 .worker.v1.DeleteScheduleRequest\x1a!.worker.v1.DeleteScheduleResponse\x12R\n" +
	"\rPauseSchedule\x12\x1f.worker.v1.PauseScheduleRequest\x1a .worker.v1.PauseScheduleResponse\x12@\n" +
	"\aListDLQ\x12\x19.worker.v1.ListDLQRequest\x1a\x1a.worker.v1.ListDLQResponse\x12O\n" +
	"\fPauseDequeue\x12\x1e.worker.v1.PauseDequeueRequest\x1a\x1f.worker.v1.PauseDequeueResponse\x12R\n" +
	"\rResumeDequeue\x12\x1f.worker.v1.ResumeDequeueRequest\x1a .worker.v1.ResumeDequeueResponse\x12F\n" +
	"\tReplayDLQ\x12\x1b.worker.v1.ReplayDLQRequest\x1a\x1c.worker.v1.ReplayDLQResponse\x12R\n" +
	"\rReplayDLQByID\x12\x1f.worker.v1.ReplayDLQByIDRequest\x1a .worker.v1.ReplayDLQByIDResponseB\x94\x01\n" +
	"\rcom.worker.v1B\n" +
	"AdminProtoP\x01Z2github.com/hyp3rd/go-worker/pkg/worker/v1;workerpb\xa2\x02\x03WXX\xaa\x02\tWorker.V1\xca\x02\tWorker\\V1\xe2\x02\x15Worker\\V1\\GPBMetadata\xea\x02\n" +
	"Worker::V1b\x06proto3"

var (
	file_worker_v1_admin_proto_rawDescOnce sync.Once
	file_worker_v1_admin_proto_rawDescData []byte
)

func file_worker_v1_admin_proto_rawDescGZIP() []byte {
	file_worker_v1_admin_proto_rawDescOnce.Do(func() {
		file_worker_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_v1_admin_proto_rawDesc), len(file_worker_v1_admin_proto_rawDesc)))
	})
	return file_worker_v1_admin_proto_rawDescData
}

var (
	file_worker_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
	file_worker_v1_admin_proto_goTypes  = []any{
		(*GetOverviewRequest)(nil),            // 0: worker.v1.GetOverviewRequest
		(*OverviewStats)(nil),                 // 1: worker.v1.OverviewStats
		(*CoordinationStatus)(nil),            // 2: worker.v1.CoordinationStatus
		(*AdminActionCounters)(nil),           // 3: worker.v1.AdminActionCounters
		(*GetOverviewResponse)(nil),           // 4: worker.v1.GetOverviewResponse
		(*GetHealthRequest)(nil),              // 5: worker.v1.GetHealthRequest
		(*GetHealthResponse)(nil),             // 6: worker.v1.GetHealthResponse
		(*QueueSummary)(nil),                  // 7: worker.v1.QueueSummary
		(*ListQueuesRequest)(nil),             // 8: worker.v1.ListQueuesRequest
		(*ListQueuesResponse)(nil),            // 9: worker.v1.ListQueuesResponse
		(*GetQueueRequest)(nil),               // 10: worker.v1.GetQueueRequest
		(*GetQueueResponse)(nil),              // 11: worker.v1.GetQueueResponse
		(*UpdateQueueWeightRequest)(nil),      // 12: worker.v1.UpdateQueueWeightRequest
		(*UpdateQueueWeightResponse)(nil),     // 13: worker.v1.UpdateQueueWeightResponse
		(*ResetQueueWeightRequest)(nil),       // 14: worker.v1.ResetQueueWeightRequest
		(*ResetQueueWeightResponse)(nil),      // 15: worker.v1.ResetQueueWeightResponse
		(*ScheduleEntry)(nil),                 // 16: worker.v1.ScheduleEntry
		(*ScheduleFactory)(nil),               // 17: worker.v1.ScheduleFactory
		(*ScheduleEvent)(nil),                 // 18: worker.v1.ScheduleEvent
		(*ListScheduleFactoriesRequest)(nil),  // 19: worker.v1.ListScheduleFactoriesRequest
		(*ListScheduleFactoriesResponse)(nil), // 20: worker.v1.ListScheduleFactoriesResponse
		(*ListScheduleEventsRequest)(nil),     // 21: worker.v1.ListScheduleEventsRequest
		(*ListScheduleEventsResponse)(nil),    // 22: worker.v1.ListScheduleEventsResponse
		(*ListSchedulesRequest)(nil),          // 23: worker.v1.ListSchedulesRequest
		(*ListSchedulesResponse)(nil),         // 24: worker.v1.ListSchedulesResponse
		(*CreateScheduleRequest)(nil),         // 25: worker.v1.CreateScheduleRequest
		(*CreateScheduleResponse)(nil),        // 26: worker.v1.CreateScheduleResponse
		(*DeleteScheduleRequest)(nil),         // 27: worker.v1.DeleteScheduleRequest
		(*DeleteScheduleResponse)(nil),        // 28: worker.v1.DeleteScheduleResponse
		(*PauseScheduleRequest)(nil),          // 29: worker.v1.PauseScheduleRequest
		(*PauseScheduleResponse)(nil),         // 30: worker.v1.PauseScheduleResponse
		(*DLQEntry)(nil),                      // 31: worker.v1.DLQEntry
		(*ListDLQRequest)(nil),                // 32: worker.v1.ListDLQRequest
		(*ListDLQResponse)(nil),               // 33: worker.v1.ListDLQResponse
		(*PauseDequeueRequest)(nil),           // 34: worker.v1.PauseDequeueRequest
		(*PauseDequeueResponse)(nil),          // 35: worker.v1.PauseDequeueResponse
		(*ResumeDequeueRequest)(nil),          // 36: worker.v1.ResumeDequeueRequest
		(*ResumeDequeueResponse)(nil),         // 37: worker.v1.ResumeDequeueResponse
		(*ReplayDLQRequest)(nil),              // 38: worker.v1.ReplayDLQRequest
		(*ReplayDLQResponse)(nil),             // 39: worker.v1.ReplayDLQResponse
		(*ReplayDLQByIDRequest)(nil),          // 40: worker.v1.ReplayDLQByIDRequest
		(*ReplayDLQByIDResponse)(nil),         // 41: worker.v1.ReplayDLQByIDResponse
		nil,                                   // 42: worker.v1.ScheduleEvent.MetadataEntry
	}
)

var file_worker_v1_admin_proto_depIdxs = []int32{
	1,  // 0: worker.v1.GetOverviewResponse.stats:type_name -> worker.v1.OverviewStats
	2,  // 1: worker.v1.GetOverviewResponse.coordination:type_name -> worker.v1.CoordinationStatus
	3,  // 2: worker.v1.GetOverviewResponse.actions:type_name -> worker.v1.AdminActionCounters
	7,  // 3: worker.v1.ListQueuesResponse.queues:type_name -> worker.v1.QueueSummary
	7,  // 4: worker.v1.GetQueueResponse.queue:type_name -> worker.v1.QueueSummary
	7,  // 5: worker.v1.UpdateQueueWeightResponse.queue:type_name -> worker.v1.QueueSummary
	7,  // 6: worker.v1.ResetQueueWeightResponse.queue:type_name -> worker.v1.QueueSummary
	42, // 7: worker.v1.ScheduleEvent.metadata:type_name -> worker.v1.ScheduleEvent.MetadataEntry
	17, // 8: worker.v1.ListScheduleFactoriesResponse.factories:type_name -> worker.v1.ScheduleFactory
	18, // 9: worker.v1.ListScheduleEventsResponse.events:type_name -> worker.v1.ScheduleEvent
	16, // 10: worker.v1.ListSchedulesResponse.schedules:type_name -> worker.v1.ScheduleEntry
	16, // 11: worker.v1.CreateScheduleResponse.schedule:type_name -> worker.v1.ScheduleEntry
	16, // 12: worker.v1.PauseScheduleResponse.schedule:type_name -> worker.v1.ScheduleEntry
	31, // 13: worker.v1.ListDLQResponse.entries:type_name -> worker.v1.DLQEntry
	5,  // 14: worker.v1.AdminService.GetHealth:input_type -> worker.v1.GetHealthRequest
	0,  // 15: worker.v1.AdminService.GetOverview:input_type -> worker.v1.GetOverviewRequest
	8,  // 16: worker.v1.AdminService.ListQueues:input_type -> worker.v1.ListQueuesRequest
	10, // 17: worker.v1.AdminService.GetQueue:input_type -> worker.v1.GetQueueRequest
	12, // 18: worker.v1.AdminService.UpdateQueueWeight:input_type -> worker.v1.UpdateQueueWeightRequest
	14, // 19: worker.v1.AdminService.ResetQueueWeight:input_type -> worker.v1.ResetQueueWeightRequest
	19, // 20: worker.v1.AdminService.ListScheduleFactories:input_type -> worker.v1.ListScheduleFactoriesRequest
	21, // 21: worker.v1.AdminService.ListScheduleEvents:input_type -> worker.v1.ListScheduleEventsRequest
	23, // 22: worker.v1.AdminService.ListSchedules:input_type -> worker.v1.ListSchedulesRequest
	25, // 23: worker.v1.AdminService.CreateSchedule:input_type -> worker.v1.CreateScheduleRequest
	27, // 24: worker.v1.AdminService.DeleteSchedule:input_type -> worker.v1.DeleteScheduleRequest
	29, // 25: worker.v1.AdminService.PauseSchedule:input_type -> worker.v1.PauseScheduleRequest
	32, // 26: worker.v1.AdminService.ListDLQ:input_type -> worker.v1.ListDLQRequest
	34, // 27: worker.v1.AdminService.PauseDequeue:input_type -> worker.v1.PauseDequeueRequest
	36, // 28: worker.v1.AdminService.ResumeDequeue:input_type -> worker.v1.ResumeDequeueRequest
	38, // 29: worker.v1.AdminService.ReplayDLQ:input_type -> worker.v1.ReplayDLQRequest
	40, // 30: worker.v1.AdminService.ReplayDLQByID:input_type -> worker.v1.ReplayDLQByIDRequest
	6,  // 31: worker.v1.AdminService.GetHealth:output_type -> worker.v1.GetHealthResponse
	4,  // 32: worker.v1.AdminService.GetOverview:output_type -> worker.v1.GetOverviewResponse
	9,  // 33: worker.v1.AdminService.ListQueues:output_type -> worker.v1.ListQueuesResponse
	11, // 34: worker.v1.AdminService.GetQueue:output_type -> worker.v1.GetQueueResponse
	13, // 35: worker.v1.AdminService.UpdateQueueWeight:output_type -> worker.v1.UpdateQueueWeightResponse
	15, // 36: worker.v1.AdminService.ResetQueueWeight:output_type -> worker.v1.ResetQueueWeightResponse
	20, // 37: worker.v1.AdminService.ListScheduleFactories:output_type -> worker.v1.ListScheduleFactoriesResponse
	22, // 38: worker.v1.AdminService.ListScheduleEvents:output_type -> worker.v1.ListScheduleEventsResponse
	24, // 39: worker.v1.AdminService.ListSchedules:output_type -> worker.v1.ListSchedulesResponse
	26, // 40: worker.v1.AdminService.CreateSchedule:output_type -> worker.v1.CreateScheduleResponse
	28, // 41: worker.v1.AdminService.DeleteSchedule:output_type -> worker.v1.DeleteScheduleResponse
	30, // 42: worker.v1.AdminService.PauseSchedule:output_type -> worker.v1.PauseScheduleResponse
	33, // 43: worker.v1.AdminService.ListDLQ:output_type -> worker.v1.ListDLQResponse
	35, // 44: worker.v1.AdminService.PauseDequeue:output_type -> worker.v1.PauseDequeueResponse
	37, // 45: worker.v1.AdminService.ResumeDequeue:output_type -> worker.v1.ResumeDequeueResponse
	39, // 46: worker.v1.AdminService.ReplayDLQ:output_type -> worker.v1.ReplayDLQResponse
	41, // 47: worker.v1.AdminService.ReplayDLQByID:output_type -> worker.v1.ReplayDLQByIDResponse
	31, // [31:48] is the sub-list for method output_type
	14, // [14:31] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_worker_v1_admin_proto_init() }
func file_worker_v1_admin_proto_init() {
	if File_worker_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_v1_admin_proto_rawDesc), len(file_worker_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_worker_v1_admin_proto_goTypes,
		DependencyIndexes: file_worker_v1_admin_proto_depIdxs,
		MessageInfos:      file_worker_v1_admin_proto_msgTypes,
	}.Build()
	File_worker_v1_admin_proto = out.File
	file_worker_v1_admin_proto_goTypes = nil
	file_worker_v1_admin_proto_depIdxs = nil
}
