// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: worker/v1/payload.proto

package workerpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Example Payload
type SendEmailPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	To            string                 `protobuf:"bytes,1,opt,name=to,proto3" json:"to,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendEmailPayload) Reset() {
	*x = SendEmailPayload{}
	mi := &file_worker_v1_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendEmailPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendEmailPayload) ProtoMessage() {}

func (x *SendEmailPayload) ProtoReflect() protoreflect.Message {
	mi := &file_worker_v1_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendEmailPayload.ProtoReflect.Descriptor instead.
func (*SendEmailPayload) Descriptor() ([]byte, []int) {
	return file_worker_v1_payload_proto_rawDescGZIP(), []int{0}
}

func (x *SendEmailPayload) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendEmailPayload) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendEmailPayload) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_worker_v1_payload_proto protoreflect.FileDescriptor

const file_worker_v1_payload_proto_rawDesc = "" +
	"\n" +
	"\x17worker/v1/payload.proto\x12\tworker.v1\"P\n" +
	"\x10SendEmailPayload\x12\x0e\n" +
	"\x02to\x18\x01 \x01(\tR\x02to\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04bodyB4Z2github.com/hyp3rd/go-worker/pkg/worker/v1;workerpbb\x06proto3"

var (
	file_worker_v1_payload_proto_rawDescOnce sync.Once
	file_worker_v1_payload_proto_rawDescData []byte
)

func file_worker_v1_payload_proto_rawDescGZIP() []byte {
	file_worker_v1_payload_proto_rawDescOnce.Do(func() {
		file_worker_v1_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_worker_v1_payload_proto_rawDesc), len(file_worker_v1_payload_proto_rawDesc)))
	})
	return file_worker_v1_payload_proto_rawDescData
}

var (
	file_worker_v1_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
	file_worker_v1_payload_proto_goTypes  = []any{
		(*SendEmailPayload)(nil), // 0: worker.v1.SendEmailPayload
	}
)

var file_worker_v1_payload_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_worker_v1_payload_proto_init() }
func file_worker_v1_payload_proto_init() {
	if File_worker_v1_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_worker_v1_payload_proto_rawDesc), len(file_worker_v1_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_worker_v1_payload_proto_goTypes,
		DependencyIndexes: file_worker_v1_payload_proto_depIdxs,
		MessageInfos:      file_worker_v1_payload_proto_msgTypes,
	}.Build()
	File_worker_v1_payload_proto = out.File
	file_worker_v1_payload_proto_goTypes = nil
	file_worker_v1_payload_proto_depIdxs = nil
}
